# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b00028498ff7a3cb2a6090363214994f1e455b23c74e40f5f0a2ddffbb6e3b1088db0518f16e728c54bc23cf84d5a02c79b2ee4c0c5f21160bdb243390d1afb

test:
  secret_key_base: 7bec49f826381d0f221fc45226431c91dddf835e8588cb2ee738aa66964b19764f849ee74015126d0bd7304984cf44bbbff4c0d2ccfaa1b9687481ee57196046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
